version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.9.0.1-1
    ports:
    - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.16.109.224
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
